# Generated by Django 5.1.4 on 2025-07-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='lon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
