# Generated by Django 5.1.4 on 2025-07-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='citylat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='citylon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
