# Generated by Django 5.1.4 on 2025-07-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_attraction_citylat_attraction_citylon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='citylat',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='citylon',
        ),
        migrations.AddField(
            model_name='city',
            name='citylat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='citylon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
