# Generated by Django 5.1.4 on 2025-07-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_pasttrips_attractions_alter_pasttrips_cities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasttrips',
            old_name='cities',
            new_name='city',
        ),
    ]
