# Generated by Django 5.1.4 on 2025-07-29 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_userprofile_birthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('attractions', models.ManyToManyField(blank=True, related_name='in_daywise_trips', to='backend.attraction')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_wise_trips', to='backend.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_wise_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'city', 'day')},
            },
        ),
    ]
